include( "darkrp_modules/billiards/sv_billiards.lua" )
include( "darkrp_modules/billiards/billiards_files.lua" )
AddCSLuaFile( "darkrp_modules/billiards/cl_billiards.lua" )

resource.AddFile("materials/darkrp/DarkRPSkin.png")
resource.AddFile("materials/darkrp/DarkRPSkin2.png")
resource.AddFile("materials/darkrp/j0rpigradient3.png")
resource.AddFile("materials/darkrp/j0rpigradient4.png")
resource.AddFile("materials/darkrp/j0rpigradient5.png")
resource.AddFile("materials/darkrp/j0rpihpgradient6.png")
resource.AddFile("materials/darkrp/j0rpihpgradient2.png")
resource.AddFile("materials/darkrp/j0rpismurf2.png")
resource.AddFile("materials/darkrp/j0rpismurfnew.png")
resource.AddFile("materials/darkrp/j0rpismurfnew2.png")
resource.AddFile("materials/boowman/bg5.png")
resource.AddFile("materials/darkrp/pigeon2.png")
resource.AddFile("materials/dan/rprint/fanpart1.png")
resource.AddFile("materials/dan/rprint/fanpart2.png")

resource.AddFile("materials/darkrp/DarkRPSkin.png")
resource.AddFile("materials/darkrp/DarkRPSkin2.png")
resource.AddFile("materials/darkrp/j0rpigradient3.png")
resource.AddFile("materials/darkrp/j0rpigradient4.png")
resource.AddFile("materials/darkrp/j0rpigradient5.png")
resource.AddFile("materials/darkrp/j0rpihpgradient6.png")
resource.AddFile("materials/darkrp/j0rpihpgradient2.png")
resource.AddFile("materials/darkrp/j0rpismurf2.png")
resource.AddFile("materials/darkrp/j0rpismurfnew.png")
resource.AddFile("materials/darkrp/j0rpismurfnew2.png")
resource.AddFile("materials/boowman/bg5.png")



-- SLOTS MACHINE TEXTURES

resource.AddFile("materials/models/gmod_tower/casino/bumpmap.vtf")
resource.AddFile("materials/models/gmod_tower/casino/button.vtf")
resource.AddFile("materials/models/gmod_tower/casino/button.vmt")
resource.AddFile("materials/models/gmod_tower/casino/glass.vtf")
resource.AddFile("materials/models/gmod_tower/casino/glass.vmt")
resource.AddFile("materials/models/gmod_tower/casino/phong_exp.vtf")
resource.AddFile("materials/models/gmod_tower/casino/slotmachine.vtf")
resource.AddFile("materials/models/gmod_tower/casino/slotmachine.vmt")
resource.AddFile("materials/models/gmod_tower/casino/slotmachine2.vtf")
resource.AddFile("materials/models/gmod_tower/casino/spinner.vtf")
resource.AddFile("materials/models/gmod_tower/casino/spinner.vmt")
resource.AddFile("materials/models/gmod_tower/casino/vpm_table.vtf")
resource.AddFile("materials/models/gmod_tower/casino/vpm_table.vmt")


-- SLOT MACHINE MODELS

resource.AddFile("models/gmod_tower/casino/slotmachine.dx80.vtx")
resource.AddFile("models/gmod_tower/casino/slotmachine.dx90.vtx")
resource.AddFile("models/gmod_tower/casino/slotmachine.mdl")
resource.AddFile("models/gmod_tower/casino/slotmachine.phy")
resource.AddFile("models/gmod_tower/casino/slotmachine.sw.vtx")
resource.AddFile("models/gmod_tower/casino/slotmachine.vvd")

-- AND, FINALLY, THE SOUNDS!

resource.AddFile("sound/pt/casino/slots/slotpull.wav")
resource.AddFile("sound/pt/casino/slots/spin_loop1.wav")
resource.AddFile("sound/pt/casino/slots/winner.wav")
resource.AddFile("sound/pt/casino/slots/you_win_forever.mp3")

resource.AddWorkshop("104479831")
resource.AddWorkshop("109643223")
resource.AddWorkshop("108424005")
resource.AddWorkshop("157660704")
resource.AddWorkshop("133342076")
resource.AddWorkshop("148404710")
resource.AddWorkshop("104479034")
resource.AddWorkshop("109586003")
resource.AddWorkshop("107411755")
resource.AddWorkshop("104815552")
resource.AddWorkshop("105115318")
resource.AddWorkshop("119222908")
resource.AddWorkshop("110286060")
resource.AddWorkshop("112986621")
resource.AddWorkshop("104479467")
resource.AddWorkshop("113495466")
resource.AddWorkshop("171935748")
resource.AddWorkshop("183313434")

